/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccordRouteImport } from './routes/accord'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CounselRouteImport } from './routes/counsel'
import { Route as MobilityRouteImport } from './routes/mobility'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordRoute = AccordRouteImport.update({
  id: '/accord',
  path: '/accord',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselRoute = CounselRouteImport.update({
  id: '/counsel',
  path: '/counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityRoute = MobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accord': typeof AccordRoute
  '/admin': typeof AdminRoute
  '/counsel': typeof CounselRoute
  '/mobility': typeof MobilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accord': typeof AccordRoute
  '/admin': typeof AdminRoute
  '/counsel': typeof CounselRoute
  '/mobility': typeof MobilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accord': typeof AccordRoute
  '/admin': typeof AdminRoute
  '/counsel': typeof CounselRoute
  '/mobility': typeof MobilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accord' | '/admin' | '/counsel' | '/mobility'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accord' | '/admin' | '/counsel' | '/mobility'
  id: '__root__' | '/' | '/accord' | '/admin' | '/counsel' | '/mobility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordRoute: typeof AccordRoute
  AdminRoute: typeof AdminRoute
  CounselRoute: typeof CounselRoute
  MobilityRoute: typeof MobilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accord': {
      id: '/accord'
      path: '/accord'
      fullPath: '/accord'
      preLoaderRoute: typeof AccordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsel': {
      id: '/counsel'
      path: '/counsel'
      fullPath: '/counsel'
      preLoaderRoute: typeof CounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility': {
      id: '/mobility'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordRoute: AccordRoute,
  AdminRoute: AdminRoute,
  CounselRoute: CounselRoute,
  MobilityRoute: MobilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
